export const LOAD_MENU_SUCCESS = "LOAD_MENU_SUCCESS";
export const SAVE_MENU_SUCCESS = "SAVE_MENU_SUCCESS";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const LOAD_ORDER_SUCCESS = "LOAD_ORDER_SUCCESS";
export const SAVE_ORDER_SUCCESS = "SAVE_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
